version: 1.0.{build}
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.sln'
  version: '{version}'
  package_version: '{version}'
install:
- cmd: appveyor downloadfile https://dist.nuget.org/win-x86-commandline/v4.3.0/nuget.exe
before_build:
- cmd: nuget restore src
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
before_package:
- cmd: dotnet pack src -c release
deploy:
- provider: NuGet
  api_key:
    secure: aimcJt2jF4Ir1ZSTFIRgga4b8NsOEQA2okwSLVeXyI0qdM5jVn5OtEaMDjuLNmXr